### ISSUE TITLE
Using custom titles only

### ISSUE THREAD

**Issue by alex-marochko** [Batterii/Minor#1]
Hi! Thanks for your nice lib.

How could I turn off lib's titles, to use only my own? I want to fill whole MinorView's space with my view.

**Comment by AKiniyalocts** [comment]
Hmmm, that will take some slight rework in the api, since the titles are always created, but a good request! I'll get to it when i get some free time (or feel free to submit a PR and I'll review it). 👍

**Comment by alex-marochko** [comment]
I've got it. ) When I deleted all titles from XML, everything worked fine. Sorry for disturbing :)

**Comment by ZeeRooo** [comment]
There´s any way to set the titles direct from Java?
